### ISSUE TITLE
Feat: refactor auction specific hooks into Provider / useProvider pattern

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/dao-utils#1]

**Comment by dblodorn** [comment]
Example of this pattern is in drops utils:
https://github.com/public-assembly/zora-drops-utils/blob/main/packages/zora-drops-utils/src/context/DropsContractProvider.tsx

It would be nice to make each meaningful function a freestanding hook. I imagine what we net is a wagmi powered SDK of sorts that then gets exposed in a convenient catch all provider.

We can circle back and see which methods would be nice to also expose react agnostic functions that can be used server side, or outside of a react app.

you can use wagmi/core for this:
https://wagmi.sh/core/actions/readContract

Also we should use this for contract reads:
https://wagmi.sh/react/hooks/useContractReads

**Comment by salieflewis** [comment]
I’m trying to understand the relationship between the existing hooks, and a provider component. Am I right to say that the refactored hooks will not consume from the provider? 

And a hook that uses the context prepared by the provider will be directly consumed by components? i.e. useDropsContractProvider

Lastly, does this mean there is an all encompassing provider that supplies an array of information (auction and proposal included) or are you imagining more discrete chunks, AuctionProvider, ProposalProvider?

**Comment by dblodorn** [comment]
Hey @salieflewis yeah the provider is for shared state between components - it makes it much easier to create atomic UI components that you can compose in your app, as long as they are wrapped by the provider.

Splitting out the hooks would be nice because a user may not want to use the provider, but still have access to hooks.

And yes I think we should follow the contracts in a sense - so ProposalProvider would be for all that, and perhaps there's a high level DaoProvider that supplies all of the general Dao data. (ie. treasury, description, etc.)

Thesis is that once all of the data is in place it will be pretty quick work writing UI against it.

The drops-utils package follows this pattern and it's pretty nice to work with imo. I am looking into some optimizations for it (ie breaking the hooks out of the provider, and organizing them in a cleaner manner)

**Comment by salieflewis** [comment]
Gotcha! Going to just start writing these things as I think they're supposed to work, and you can hopefully help steer them into the proper direction!
