### ISSUE TITLE
To get most recent token minted from DAO, need to hit aggStat query instead of totalSupply

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/dao-utils#42]
cc @salieflewis @E-Rick 

[porting this issue](https://github.com/public-assembly/public-assembly-home-page/issues/53) over from the public assembly home page repo

The zora indexer total supply call doesn't work so if we are trying to return the correct number of tokens that have been minted ever by the dao (which is improtant because tokens that dont receive bids get burned and not counted in totalSupply), we have to use the aggregateStat query instead.

screenshot of what the appropriate query looks like in the [zora api playground ](https://playground.api.zora.co/)below:

![image](https://user-images.githubusercontent.com/93691906/222622463-fe31fa03-d3dc-4aca-935f-facc9a1ef85e.png)

**Comment by salieflewis** [comment]
Working on this now

https://github.com/public-assembly/dao-utils/pull/43

**Comment by salieflewis** [comment]
This should be resolved with dao-utils@0.0.9
