### ISSUE TITLE
useDaoCollectionQuery missing hook 

### ISSUE THREAD

**Issue by breath-imager** [public-assembly/dao-utils#53]
I'm getting this error when it's called in TokenExplorer

It seems to be missing in this declaration files

index.d.ts line 21:
import { useCountdown, useDaoAuctionQuery, useDaoToken, useBidder, useActiveAuction, useNounsProtocol } from './hooks';

also line 45:
/**
 * Hooks
 */
useCountdown, useDaoAuctionQuery, useDaoToken, useBidder, useActiveAuction, useNounsProtocol, 

![Screenshot from 2023-03-15 18-42-03](https://user-images.githubusercontent.com/14821226/225464719-b6bd95c3-2ae9-487e-8342-cd0423b3b326.png)

**Comment by salieflewis** [comment]
Can you provide more context for this error?

**Comment by salieflewis** [comment]
Resolved with 0.0.12
